version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysqljogo
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: dbmysql
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bancodados
    networks:
      - net
  admineruaa:
    image: adminer
    restart: always
    ports:
      - 9091:8000
    networks:
      - net

networks:
  net:
    driver: bridge